# Generated by Django 4.0.5 on 2022-07-05 13:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('albums', '0004_alter_album_created_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='album',
            name='created_at',
        ),
    ]
