# Generated by Django 4.0.5 on 2022-07-05 13:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('albums', '0007_rename_artist_album_artists'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Artist',
        ),
    ]
