# Generated by Django 4.0.5 on 2022-07-05 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('albums', '0009_artist'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artist',
            name='albums',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
