# Generated by Django 4.0.6 on 2022-07-05 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('albums', '0012_alter_album_created_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='album',
            name='artists',
        ),
        migrations.AddField(
            model_name='album',
            name='artists',
            field=models.ManyToManyField(to='albums.artist'),
        ),
        migrations.RemoveField(
            model_name='artist',
            name='albums',
        ),
        migrations.AddField(
            model_name='artist',
            name='albums',
            field=models.ManyToManyField(to='albums.album'),
        ),
    ]
