# Generated by Django 4.0.6 on 2022-07-05 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('albums', '0013_remove_album_artists_album_artists_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='album',
            name='artists',
            field=models.ManyToManyField(blank=True, null=True, to='albums.artist'),
        ),
        migrations.AlterField(
            model_name='artist',
            name='albums',
            field=models.ManyToManyField(blank=True, null=True, to='albums.album'),
        ),
    ]
