# Generated by Django 4.0.6 on 2022-07-05 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('albums', '0016_rename_artists_album_artist_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='album',
            name='artist',
        ),
        migrations.RemoveField(
            model_name='artist',
            name='album',
        ),
        migrations.AddField(
            model_name='album',
            name='artists',
            field=models.ManyToManyField(blank=True, to='albums.artist'),
        ),
        migrations.AddField(
            model_name='artist',
            name='albums',
            field=models.ManyToManyField(blank=True, to='albums.album'),
        ),
    ]
