# Generated by Django 4.0.6 on 2022-07-05 18:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('albums', '0017_remove_album_artist_remove_artist_album_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='artist',
            name='albums',
        ),
    ]
