# Generated by Django 4.0.6 on 2022-07-05 18:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('albums', '0019_alter_album_artists'),
    ]

    operations = [
        migrations.RenameField(
            model_name='artist',
            old_name='artist_name',
            new_name='name',
        ),
    ]
